#!/bin/bash

set bell-style visible # no noise

# bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

BASH_COMPLETION_FILES=$(find `brew --prefix`/etc/bash_completion.d  \( -type l -o -type f \) -mindepth 1 -maxdepth 1)
for file in ${BASH_COMPLETION_FILES[@]}; do
  source $file
done;
unset file;

# nvm
mkdir -p "${HOME}/.nvm"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# brew
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# ansible
export ANSIBLE_NOCOWS=1